from functools import cache
import torch
from jaxtyping import Float
from torch import Tensor
import einops
import opt_einsum as oe
from typing import Any, Callable, Callable
from functools import partial
from collections import defaultdict

from mlp_kprop.partitions import Vec
from mlp_kprop.flop_utils import *

type Tower = dict[int, Float[Tensor, "*n"]]  # d -> (n,)*d.

@flop_name('is_symmetric', factor=0) # No need to do this if we have symmetric tensor kernels, so they don't count towards flops.
def is_symmetric(A: Float[Tensor, '*n'], vec: Optional[Vec] = None) -> bool:
    """
    Check whether `A` is invariant under all axis-permutations that preserve vec.

    A permutation π ∈ S_d preserves vec iff vec[i] == vec[π(i)] for all i, i.e. π may
    permute axes only within each equivalence class of equal vec-entries.

    Examples:
      - vec = (1, 1, 2): only require symmetry under swapping axes 0 and 1.
      - vec = (1, 1, 1): this reduces to full symmetry of all d axes.
      - vec = (1, 2, 3): no nontrivial permutations preserve vec, so any tensor of the
        right shape passes.

    We use that 
        - The symmetry group of vec is the direct product of symmetric groups on each equivalence class.
        - Each symmetric group S_k is generated by a transposition (p0 p1) and a k-cycle (p0 p1 ... p_{k-1}).
    Thus O(C * n^d) FLOPs, where C <= 2 * (num equivalence classes of vec) <= 2d.
    """
    A = torch.as_tensor(A)
    if A.ndim == 0:
        return True

    d = A.ndim
    n = A.shape[0]

    if A.shape != (n,) * d:
        return False
    if d <= 1:
        return True

    if vec is None:
        vec = (1,) * d
    else:
        if len(vec) != d:
            raise ValueError(f"`vec` must have length {d} (got {len(vec)})")

    eq = torch.allclose if (A.is_floating_point() or A.is_complex()) else torch.equal

    # Group axis indices by their vec-label.
    classes: dict[int, list[int]] = defaultdict(list)
    for i, lbl in enumerate(vec):
        classes[lbl].append(i)

    # For each class of size k, check invariance under a generating set of S_k:
    #   - a transposition (p0 p1)
    #   - a k-cycle (p0 p1 ... p_{k-1})  (only needed if k>2)
    for axes in classes.values():
        if len(axes) <= 1:
            continue
        axes = sorted(axes)

        # generator: swap first two axes in this class
        if not eq(A, A.transpose(axes[0], axes[1])):
            return False

        if len(axes) == 2:
            continue

        # generator: cycle the axes within this class, leaving other axes fixed
        perm = list(range(d))
        for j in range(len(axes)):
            perm[axes[j]] = axes[(j + 1) % len(axes)]
        if not eq(A, A.permute(perm)):
            return False

    return True

@flop_name('symmetrize', factor=0)  # No need to do this if we have symmetric tensor kernels, so they don't count towards flops.
def symmetrize(A: Float[Tensor, '*n'], vec: Optional[tuple[int, ...]] = None) -> Float[Tensor, '*n']:
    """
    Symmetrize an order-d tensor A of shape (n,)*d.

    If vec is given: only symmetrize with respect to permutations that preserve vec,
    i.e. permutations that only permute axes within each label-class
        I_c := { i : vec[i] == c }.
    Equivalently, average over the subgroup  ∏_c S_{I_c}.

    For each class I_c of size k, apply the recursive coset
    decomposition S_{t+1} = ⨿_{j=0}^t (j t) S_t on the axes in that class.
    Total FLOPs is O((∑_c k_c^2) n^d) ≤ O(d^2 n^d).
    """
    A = torch.as_tensor(A)
    d = A.ndim
    if d <= 1:
        return A
    if len(set(A.shape)) != 1:
        raise ValueError("Expected shape (n,...,n).")

    if vec is None:
        vec = (1,) * d

    if len(vec) != d:
        raise ValueError(f"`vec` must have length {d} (got {len(vec)})")

    classes: dict[int, list[int]] = defaultdict(list)
    for i, lbl in enumerate(vec):
        classes[lbl].append(i)

    U = A
    for axes in classes.values():
        k = len(axes)
        if k <= 1:
            continue
        axes = sorted(axes)

        V = U
        for t in range(1, k):
            acc = V.clone()  # includes identity term
            for j in range(t):
                acc.add_(V.transpose(axes[j], axes[t]))
            V = acc.div_(t + 1)
        U = V

    return U

@cache
def _get_contract_expr(*interleaved, path: list[tuple[int, ...]] | None = None) -> Callable:
    """
    Given an einsum input (expr and shapes), return the compiled contraction callable.
    We use opt_einsum's "interleaved" input format, so that the input is
        interleaved = (shapes[0], idxs[0], ..., shapes[k], idxs[k], out_idxs)
    where shapes are tuples of tensor shapes and idxs are corresponding tuples of index labels.
    If path is provided, use that contraction path; otherwise, use optimal.
    """
    return oe.contract_expression(*interleaved, optimize=path if path is not None else "optimal")

@cache
def expr_to_idxs(expr: str) -> tuple[tuple[int, ...], ...]:
    """
    Converts an einsum expression to a tuple of index tuples.
    E.g. 'a b, b c -> a c' becomes ((0, 1), (1, 2), (0, 2)).
    This is used for opt_einsum's interleaved input format.
    """
    idx_map = dict()
    idxs = []
    for x in expr.replace("->", ",").split(","):
        x_idxs = []
        if not x.strip(" "):
            # Special handling for empty output (scalar)
            idxs.append(tuple())
            continue
        for name in x.strip(" ").split(" "):
            if name not in idx_map:
                idx_map[name] = len(idx_map)
            x_idxs.append(idx_map[name])
        idxs.append(tuple(x_idxs))
    return tuple(idxs)

def cached_einsum(
    *tensors_and_expr: Tensor | str, path: list[tuple[int, ...]] | None = None
) -> Tensor:
    """
    Behavior identical to einops.einsum, but caches the contraction path for efficiency.
    Contraction path can also be specified manually.
    """
    tensors = tensors_and_expr[:-1]
    expr = tensors_and_expr[-1]
    shapes = [tuple(t.shape) for t in tensors]
    idxs = expr_to_idxs(expr)
    interleaved = tuple(sum(zip(shapes, idxs), ())) + (idxs[-1],)
    return _get_contract_expr(*interleaved, path=path)(*tensors)

def contract_W_basic(A: Float[Tensor, '*n_in'], W: Float[Tensor, 'n_out n_in']) -> Float[Tensor, '*n_out']:
    if A.ndim == 0:
        # Contract with 0 copies of W
        return A
    s = A.ndim
    A_expr = ' '.join(f'i{i}' for i in range(s))
    W_expr = ', '.join(f'j{i} i{i}' for i in range(s))
    out_expr = ' '.join(f'j{i}' for i in range(s))
    contract_expr = f'{A_expr}, {W_expr} -> {out_expr}'
    with flop_name(f'contract_W_basic', factor=contract_factor(s, n=W.shape[0])):
        ret = cached_einsum(
            *([A] + [W] * s), contract_expr
        )
    if is_symmetric(A):
        # ret is symmetric but do it explicitly to avoid numerical issues
        ret = symmetrize(ret)
    return ret

def expand(X: Tensor, positions: tuple[int, ...], d: int) -> Tensor:
    """
    View X (order len(positions)) as an order-d tensor by inserting singleton dims
    so that its original axes land exactly at `positions`.
    Sorts positions before expanding; if X is not symmetric, the result may not be what you expect.
    >>> X = torch.randn(3, 4, 5)
    >>> expand(X, (0, 2, 4), 5).shape
    torch.Size([3, 1, 4, 1, 5])
    """
    assert len(positions) == X.dim()
    pos_sorted = sorted(positions)
    p = 0
    for ax in range(d):
        if p < len(pos_sorted) and pos_sorted[p] == ax:
            p += 1
        else:
            X = X.unsqueeze(ax)
    return X

def is_scalar(x: Any) -> bool:
    return isinstance(x, (int, float)) or (isinstance(x, torch.Tensor) and x.ndim == 0)
